services:
  - type: web
    name: player-dashboard
    env: node
    buildCommand: npm install --production=false && npm run build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: MAILJET_API_KEY
        sync: false
      - key: MAILJET_SECRET_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: REACT_APP_RECAPTCHA_SITE_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://player-dashboard.onrender.com
      - key: SECURITY_HEADERS_ENABLED
        value: true
      - key: REDIS_TLS_ENABLED
        value: true
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: CORS_MAX_AGE
        value: "86400"
      - key: X_FRAME_OPTIONS
        value: "DENY"
    healthCheckPath: /
    autoDeploy: true 